### ISSUE TITLE
TypeError: class <class 'generator'> is not a legal parameter source class

### ISSUE THREAD

**Issue by jayvdb** [zuo/unittest_expander#4]
`foreach` doesnt like generators.  They would be helpful so that a generator can define the list of units that need to be created, without needing to build the list at startup, as some of the test might be skipped by user selection.

```py
tests/test_top.py:15: in TestTop
    @foreach(names)
/usr/lib/python3.7/site-packages/unittest_expander.py:1820: in foreach
    ps = paramseq(*args, **kwargs)
/usr/lib/python3.7/site-packages/unittest_expander.py:1738: in __init__
    self._init_with_param_sources(args[0])
/usr/lib/python3.7/site-packages/unittest_expander.py:1773: in _init_with_param_sources
    'legal parameter source class'.format(param_src))
E   TypeError: class <class 'generator'> (of <generator object get_top_packages at 0x7fb16fa44de0>) is not a legal parameter source class
```

**Comment by zuo** [comment]
Thank you for you feedback!

As for the issue -- as far as I remember, it was a conscious design decision *not* to defer the creation of actual test methods beyond the moment when the `@expand` decorator is applied. So that, after the call of `expand`, no more magic is involved: we have just a regular test class (that contains more or less, already generated, regular test methods).

Note, however, that you can ~~apply~~ pass a *generator function* to `@foreach` or to `@paramseq` (and that such a generator function can take the test class as its sole parameter), e.g.:

```python
def my_cases(test_cls):
    yield param(foo='a', bar=42).label('A-42!')
    yield param(foo='b', bar=43)
    ...

@expand
class MyTest(unittest.TestCase):
    ...
    @foreach(my_cases)
    def test_sth(self, foo, bar):
        ...
```

or even:

```python
@paramseq  # creating reusable+composable paramseq instance
def my_cases(test_cls):
    yield param(foo='a', bar=42).label('A-42!')
    yield param(foo='b', bar=43)
    ...

@expand
class MyTest(unittest.TestCase):
    ...
    @foreach(my_cases)
    def test_sth(self, foo, bar):
        ...
    @foreach(my_cases + [param(foo='c', bar=44)])
    def test_sth_else(self, foo, bar):
        ...

@expand
class MyAnotherTest(unittest.TestCase):
    ...
    @foreach(my_cases + ['c'])
    def test_sth(self, foo, bar=1):
        ...
```

It does *not*, of course, make it possible to defer any test method generation beyond the point when `expand` is called with a particular class as its argument.

**Comment by zuo** [comment]
But why -- even only in this context (discussed above in my previous comment) -- `@foreach` (as well as `@paramseq`) does not accept *generator iterators*, or any other kinds of *iterators*, even though it *does* accept *generator functions* as well as *sequences*, *sets* etc.?

That was also a conscious design decision: iterators (including but not limited to generator-made ones) are *lossy* stateful objects -- in particular, once such an object is exhausted it cannot produce items anymore (and then, as *iterable*, is perceived as empty one).

Therefore, accepting them by `@foreach`/`@paramseq` would either lead to nasty (because exception-less) "iterable-seen-as-empty" bugs, or it would need some special-casing (so that, for example, an empty iterator would cause an exception...).

So I decided that disallowing them is a simpler and clearer solution.

**Comment by zuo** [comment]
For the reasons described above I decided that the status quo is OK.
