### ISSUE TITLE
Deprecation Warnings with python 3.8

### ISSUE THREAD

**Issue by VaeterchenFrost** [zuo/unittest_expander#5]
I ran [pytest](https://docs.pytest.org/en/latest/getting-started.html) on my project using unittest-expander v0.3.1 and got two deprecation warnings that might be helpful for further development of the expander:

```unittest_expander.py:1784: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working                                        collections.Callable)```

and 

```unittest_expander.py:1863: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()                                                                                arg_spec = inspect.getargspec(base_func) ```

With best regards - very thankful for your project!

**Comment by zuo** [comment]
Hello.

@VaeterchenFrost Big thanks for you contribution!

I apologise for such a long inactivity -- for personal reasons I was unable to actively maintain the project, but now that will change.

When it comes to the problems you pointed out, they have already been fixed in the master branch.

I hope I'll be able to release a new stable version in the coming weeks... 

Best regards!

**Comment by zuo** [comment]
Fixes in master, next release will include them, so the issue can be closed.
